"""Generate a standalone product repository from a ProductPlan + blueprint."""

from __future__ import annotations

import json
import os
import shutil
import subprocess
from pathlib import Path
from typing import Any, Dict, Optional

from app.cerebrum_product_kernel.provenance import build_provenance, hash_tree, write_provenance
from app.factory.blueprint import ProductBlueprint, blueprint_to_dict
from app.factory.planner import CapabilityPlanner, ProductPlan


class ProductGenerator:
    def __init__(
        self,
        blueprint: ProductBlueprint,
        plan: Optional[ProductPlan] = None,
        *,
        blocks_root: Optional[Path] = None,
        factory_shelf: Optional[Path] = None,
        factory_commit: str = "unknown",
        blocks_commit: str = "unknown",
    ):
        self.blueprint = blueprint
        self.planner = CapabilityPlanner(blocks_root, factory_shelf)
        self.plan = plan or self.planner.plan(blueprint)
        self.factory_commit = factory_commit
        self.blocks_commit = blocks_commit
        self.blocks_root = blocks_root

    def generate(self, output_dir: Path | str, *, clean: bool = True) -> Dict[str, Any]:
        out = Path(output_dir).resolve()
        if clean and out.exists():
            shutil.rmtree(out)
        out.mkdir(parents=True, exist_ok=True)

        self._write_readme(out)
        self._write_pyproject(out)
        self._write_app(out)
        self._write_actions(out)
        self._write_ui_stub(out)
        self._write_connectors(out)
        self._copy_referenced_blocks(out)
        self._write_blueprint_copy(out)
        self._write_edge_profile(out)

        plan_dict = self.plan.to_dict()
        inputs_hash = hash_tree(out)
        prov = build_provenance(
            product_id=self.blueprint.product_id,
            blueprint_id=f"{self.blueprint.product_id}:{self.blueprint.schema_version}",
            factory_commit=self.factory_commit,
            blocks_commit=self.blocks_commit,
            plan=plan_dict,
            inputs_hash=inputs_hash,
        )
        write_provenance(out / "docs" / "provenance" / "provenance.json", prov)
        write_provenance(out / "factory_plan.json", plan_dict)

        # Re-hash excluding volatile provenance timestamp by rewriting with stable inputs_hash only
        return {
            "output_dir": str(out),
            "inputs_hash": inputs_hash,
            "product_id": self.blueprint.product_id,
            "plan": plan_dict,
            "provenance": prov,
        }

    def _write_readme(self, out: Path) -> None:
        bp = self.blueprint
        text = f"""# {bp.product_name}

Generated by **CerebrumDev.ai** Factory from `{bp.schema_version}`.

- **Product id:** `{bp.product_id}`
- **Vertical:** {bp.vertical}
- **Summary:** {bp.summary}

Do not hand-edit durable capabilities here. Fix the Factory / Blocks / kernel and regenerate.

## Provenance

See `docs/provenance/provenance.json` and `factory_plan.json`.
"""
        (out / "README.md").write_text(text, encoding="utf-8")

    def _write_pyproject(self, out: Path) -> None:
        (out / "requirements.txt").write_text(
            "fastapi>=0.115.0\npydantic>=2.0\nuvicorn>=0.30\npyyaml>=6.0\n",
            encoding="utf-8",
        )

    def _write_app(self, out: Path) -> None:
        app = out / "app"
        app.mkdir(parents=True, exist_ok=True)
        (app / "__init__.py").write_text(
            f'"""Generated product package for {self.blueprint.product_id}."""\n'
            f'PRODUCT_ID = "{self.blueprint.product_id}"\n'
            f'VERTICAL = "{self.blueprint.vertical}"\n',
            encoding="utf-8",
        )
        # Vendor neutralized kernel contract into generated product
        kernel_src = Path(__file__).resolve().parents[1] / "cerebrum_product_kernel"
        kernel_dst = app / "cerebrum_product_kernel"
        if kernel_dst.exists():
            shutil.rmtree(kernel_dst)
        shutil.copytree(
            kernel_src,
            kernel_dst,
            ignore=shutil.ignore_patterns("__pycache__", "*.pyc"),
        )
        # Rewrite imports inside generated copy to app.cerebrum_product_kernel
        for py in kernel_dst.rglob("*.py"):
            text = py.read_text(encoding="utf-8")
            py.write_text(
                text.replace(
                    "from app.cerebrum_product_kernel",
                    "from app.cerebrum_product_kernel",
                ),
                encoding="utf-8",
            )

        (app / "main.py").write_text(
            f'''"""Generated FastAPI entrypoint for {self.blueprint.product_id}."""

from fastapi import FastAPI

app = FastAPI(title="{self.blueprint.product_name}", version="1.0.0")


@app.get("/health")
def health():
    return {{
        "ok": True,
        "product_id": "{self.blueprint.product_id}",
        "vertical": "{self.blueprint.vertical}",
        "human_authority": {str(self.blueprint.human_authority)},
    }}


@app.get("/v1/capabilities")
def capabilities():
    import json
    from pathlib import Path
    plan = json.loads((Path(__file__).resolve().parents[1] / "factory_plan.json").read_text())
    return plan
''',
            encoding="utf-8",
        )

    def _write_actions(self, out: Path) -> None:
        actions_dir = out / "app" / "actions"
        actions_dir.mkdir(parents=True, exist_ok=True)
        specs = []
        for cap in self.plan.capabilities:
            action_name = cap.capability_id.replace("-", "_")
            domain = self.blueprint.vertical.replace("-", "_")
            # action_id must be domain.action
            action_id = f"{domain}.{action_name}"
            specs.append(
                {
                    "action_id": action_id,
                    "capability_id": cap.capability_id,
                    "strategy": cap.strategy,
                    "block_ids": cap.block_ids,
                    "notes": cap.notes,
                }
            )
            mod = actions_dir / f"{action_name}.py"
            mod.write_text(
                f'''"""Generated action module for {action_id} (strategy={cap.strategy})."""

from __future__ import annotations

from typing import Any, Dict

# Strategy: {cap.strategy}
# Blocks: {", ".join(cap.block_ids) or "(none — kernel/GENERATE)"}


async def handle(context: Dict[str, Any], arguments: Dict[str, Any]) -> Dict[str, Any]:
    return {{
        "action_id": "{action_id}",
        "capability_id": "{cap.capability_id}",
        "echo": arguments,
        "status": "success",
        "strategy": "{cap.strategy}",
        "tenant_id": context.get("tenant_id"),
    }}
''',
                encoding="utf-8",
            )
        (actions_dir / "__init__.py").write_text(
            "ACTION_CATALOG = " + json.dumps(specs, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )

    def _write_ui_stub(self, out: Path) -> None:
        ui = out / "frontend" / "src"
        ui.mkdir(parents=True, exist_ok=True)
        modules = self.blueprint.ui_modules or ["command_center"]
        (ui / "App.tsx").write_text(
            "/* Generated UI shell — modules: "
            + ", ".join(modules)
            + " */\nexport default function App(){return <main><h1>"
            + self.blueprint.product_name
            + "</h1></main>}\n",
            encoding="utf-8",
        )
        (out / "frontend" / "package.json").write_text(
            json.dumps(
                {"name": self.blueprint.product_id, "private": True, "version": "1.0.0"},
                indent=2,
            )
            + "\n",
            encoding="utf-8",
        )

    def _write_connectors(self, out: Path) -> None:
        conn = out / "app" / "connectors"
        conn.mkdir(parents=True, exist_ok=True)
        items = []
        for c in self.blueprint.connectors:
            items.append({"id": c, "status": "not_implemented", "honest": True})
            (conn / f"{c}.py").write_text(
                f'"""Honest stub connector: {c}."""\n\nSTATUS = "not_implemented"\n',
                encoding="utf-8",
            )
        (conn / "__init__.py").write_text(
            "CONNECTORS = " + json.dumps(items, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )

    def _copy_referenced_blocks(self, out: Path) -> None:
        dest = out / "vendor" / "blocks"
        dest.mkdir(parents=True, exist_ok=True)
        mirror = Path(__file__).resolve().parent / "vendor_blocks_mirror"
        registry = Path(self.blocks_root) / "block_registry" if self.blocks_root else None
        for bid in self.plan.dual_registered_blocks:
            src = registry / bid if registry else None
            if src and src.exists():
                shutil.copytree(src, dest / bid, dirs_exist_ok=True)
                continue
            # Fall back to the vendor mirror when the external registry is unavailable
            mirror_src = mirror / bid
            if mirror_src.exists():
                shutil.copytree(mirror_src, dest / bid, dirs_exist_ok=True)

    def _write_blueprint_copy(self, out: Path) -> None:
        docs = out / "docs" / "blueprint"
        docs.mkdir(parents=True, exist_ok=True)
        (docs / "product_blueprint.json").write_text(
            json.dumps(blueprint_to_dict(self.blueprint), indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )

    def _write_edge_profile(self, out: Path) -> None:
        profile = {
            "edge_profile": self.blueprint.edge_profile,
            "human_authority": self.blueprint.human_authority,
            "isolation": "property",
            "pii_in_learning": False,
        }
        (out / "docs" / "edge_profile.json").write_text(
            json.dumps(profile, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )


def git_head(repo: Path) -> str:
    try:
        r = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=repo,
            capture_output=True,
            text=True,
            check=False,
        )
        if r.returncode == 0:
            return r.stdout.strip()
    except OSError:
        pass
    return "unknown"
