"""Generate a standalone product repository from a ProductPlan + blueprint."""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
from pathlib import Path
from typing import Any, Dict, Optional

from app.cerebrum_product_kernel.provenance import build_provenance, hash_tree, write_provenance
from app.factory.blueprint import ProductBlueprint, blueprint_to_dict
from app.factory.hat_adapter import build_hat_manifests, build_workflows
from app.factory.planner import CapabilityPlanner, ProductPlan
from app.factory.resident_engineer import write_resident_engineer, write_store_docs
from app.product_dna.emit import emit_product_dna
from app.resident_engineer.ship.inject import inject_resident_runtime


class ProductGenerator:
    def __init__(
        self,
        blueprint: ProductBlueprint,
        plan: Optional[ProductPlan] = None,
        *,
        blocks_root: Optional[Path] = None,
        factory_shelf: Optional[Path] = None,
        factory_commit: str = "unknown",
        blocks_commit: str = "unknown",
        product_dna_version: str = "1.0.0",
        pin_versions: Optional[Dict[str, str]] = None,
    ):
        self.blueprint = blueprint
        self.planner = CapabilityPlanner(blocks_root, factory_shelf)
        self.plan = plan or self.planner.plan(blueprint)
        self.factory_commit = factory_commit
        self.blocks_commit = blocks_commit
        self.blocks_root = blocks_root
        self.product_dna_version = product_dna_version
        self.pin_versions = dict(pin_versions or {})

    def generate(self, output_dir: Path | str, *, clean: bool = True) -> Dict[str, Any]:
        out = Path(output_dir).resolve()
        if clean and out.exists():
            shutil.rmtree(out)
        out.mkdir(parents=True, exist_ok=True)

        # Resident Engineer first — never bolted on after platform modules
        re_meta = write_resident_engineer(
            out,
            self.blueprint,
            self.plan,
            blocks_commit=self.blocks_commit,
            factory_commit=self.factory_commit,
        )
        write_store_docs(out)

        self._write_readme(out)
        self._write_pyproject(out)
        self._write_app(out)
        actions = self._write_actions(out)
        agents = self._write_hats(out)
        workflows = self._write_workflows(out)
        self._write_ui_stub(out)
        self._write_connectors(out)
        self._copy_referenced_blocks(out)
        self._write_blueprint_copy(out)
        self._write_edge_profile(out)
        self._write_certification_scaffold(out)
        if self.blueprint.vertical == "estate":
            self._write_estate_kit_surfaces(out)
        self._write_runtime_packaging(out)

        # Product DNA after catalogs exist — sole Resident Mode understanding surface.
        change_events = []
        build_event = (
            out / "product-agent" / "build_events" / "0001_resident_engineer_created.json"
        )
        if build_event.is_file():
            try:
                change_events.append(json.loads(build_event.read_text(encoding="utf-8")))
            except json.JSONDecodeError:
                change_events = []
        dna_meta = emit_product_dna(
            out,
            self.blueprint,
            self.plan,
            factory_commit=self.factory_commit,
            blocks_commit=self.blocks_commit,
            actions=actions,
            agents=agents,
            workflows=workflows,
            change_events=change_events,
            product_dna_version=self.product_dna_version,
            pin_versions=self.pin_versions,
        )
        # Resident Mode runtime package (flag-gated at runtime; always shipped)
        re_runtime = inject_resident_runtime(out)

        plan_dict = self.plan.to_dict()
        inputs_hash = hash_tree(out)
        prov = build_provenance(
            product_id=self.blueprint.product_id,
            blueprint_id=f"{self.blueprint.product_id}:{self.blueprint.schema_version}",
            factory_commit=self.factory_commit,
            blocks_commit=self.blocks_commit,
            plan=plan_dict,
            inputs_hash=inputs_hash,
        )
        write_provenance(out / "docs" / "provenance" / "provenance.json", prov)
        write_provenance(out / "factory_plan.json", plan_dict)

        return {
            "output_dir": str(out),
            "inputs_hash": inputs_hash,
            "product_id": self.blueprint.product_id,
            "plan": plan_dict,
            "provenance": prov,
            "resident_engineer": re_meta,
            "product_dna": dna_meta,
            "resident_runtime": re_runtime,
        }

    def _write_readme(self, out: Path) -> None:
        bp = self.blueprint
        text = f"""# {bp.product_name}

Generated by **CerebrumDev.ai** Factory from `{bp.schema_version}`.

- **Product id:** `{bp.product_id}`
- **Vertical:** {bp.vertical}
- **Summary:** {bp.summary}

Do not hand-edit durable capabilities here. Fix the Factory / Blocks / kernel and regenerate.

## Provenance

See `docs/provenance/provenance.json` and `factory_plan.json`.
"""
        (out / "README.md").write_text(text, encoding="utf-8")

    def _write_pyproject(self, out: Path) -> None:
        (out / "requirements.txt").write_text(
            "fastapi>=0.115.0\npydantic>=2.0\nuvicorn>=0.30\npyyaml>=6.0\n",
            encoding="utf-8",
        )

    def _write_app(self, out: Path) -> None:
        app = out / "app"
        app.mkdir(parents=True, exist_ok=True)
        (app / "__init__.py").write_text(
            f'"""Generated product package for {self.blueprint.product_id}."""\n'
            f'PRODUCT_ID = "{self.blueprint.product_id}"\n'
            f'VERTICAL = "{self.blueprint.vertical}"\n',
            encoding="utf-8",
        )
        # Vendor neutralized kernel contract into generated product
        kernel_src = Path(__file__).resolve().parents[1] / "cerebrum_product_kernel"
        kernel_dst = app / "cerebrum_product_kernel"
        if kernel_dst.exists():
            shutil.rmtree(kernel_dst)
        shutil.copytree(
            kernel_src,
            kernel_dst,
            ignore=shutil.ignore_patterns("__pycache__", "*.pyc"),
        )
        # Rewrite imports inside generated copy to app.cerebrum_product_kernel
        for py in kernel_dst.rglob("*.py"):
            text = py.read_text(encoding="utf-8")
            py.write_text(
                text.replace(
                    "from app.cerebrum_product_kernel",
                    "from app.cerebrum_product_kernel",
                ),
                encoding="utf-8",
            )

        (app / "main.py").write_text(
            f'''"""Generated FastAPI entrypoint for {self.blueprint.product_id}."""

from fastapi import FastAPI

app = FastAPI(title="{self.blueprint.product_name}", version="1.0.0")


@app.get("/health")
def health():
    return {{
        "ok": True,
        "product_id": "{self.blueprint.product_id}",
        "vertical": "{self.blueprint.vertical}",
        "human_authority": {str(self.blueprint.human_authority)},
    }}


@app.get("/v1/capabilities")
def capabilities():
    import json
    from pathlib import Path
    plan = json.loads((Path(__file__).resolve().parents[1] / "factory_plan.json").read_text())
    return plan


@app.get("/v1/agents")
def agents():
    import json
    from pathlib import Path
    root = Path(__file__).resolve().parent / "agents" / "manifests"
    return [json.loads(p.read_text()) for p in sorted(root.glob("*.json"))]


@app.get("/v1/workflows")
def workflows():
    import json
    from pathlib import Path
    path = Path(__file__).resolve().parent / "workflows" / "workflows.json"
    return json.loads(path.read_text())


# Estate kit surfaces (demo fixtures + dual RAG) are mounted when present.
try:
    from app.estate_kit import router as estate_kit_router

    app.include_router(estate_kit_router)
except ImportError:
    pass
''',
            encoding="utf-8",
        )

    def _write_estate_kit_surfaces(self, out: Path) -> None:
        """Emit demo fixtures + dual RAG API for estate vertical products."""
        import textwrap

        kit_fixtures = (
            Path(__file__).resolve().parent
            / "kits"
            / "private_estate_operations"
            / "fixtures"
            / "demo_estate.json"
        )
        data_dir = out / "data" / "demo"
        data_dir.mkdir(parents=True, exist_ok=True)
        if kit_fixtures.is_file():
            shutil.copy2(kit_fixtures, data_dir / "estate_fixtures.json")
        else:
            (data_dir / "estate_fixtures.json").write_text(
                json.dumps({"properties": [], "honesty": "fixtures missing at generate"}, indent=2)
                + "\n",
                encoding="utf-8",
            )

        dual_rag = {
            "schema_version": "1.0.0",
            "layers": {
                "1": {
                    "id": "sop_standards",
                    "name": "SOP / House Manual / global standards",
                    "index": "steward_sop_v1",
                    "source_field": "sop_corpus",
                    "blocks": ["document_engine", "knowledge", "vector_search"],
                },
                "2": {
                    "id": "estate_documents",
                    "name": "Estate documents (separately indexed)",
                    "index": "steward_estate_docs_v1",
                    "source_field": "estate_documents",
                    "blocks": ["document_engine", "knowledge", "vector_search"],
                },
            },
            "honesty": (
                "Indices are fixture-backed for certification demos; production "
                "embeddings require knowledge/vector_search block runtime."
            ),
        }
        rag_docs = out / "docs" / "rag"
        rag_docs.mkdir(parents=True, exist_ok=True)
        (rag_docs / "dual_rag.json").write_text(
            json.dumps(dual_rag, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )

        estate_mod = out / "app" / "estate_kit"
        estate_mod.mkdir(parents=True, exist_ok=True)
        (estate_mod / "__init__.py").write_text(
            '"""Factory-generated estate kit surfaces (demo + dual RAG)."""\n'
            "from app.estate_kit.router import router\n\n"
            '__all__ = ["router"]\n',
            encoding="utf-8",
        )
        (estate_mod / "router.py").write_text(
            textwrap.dedent(
                '''\
                """Estate demo fixtures + dual RAG query (Factory-generated)."""

                from __future__ import annotations

                import json
                from pathlib import Path
                from typing import Any, Dict, List, Optional

                from fastapi import APIRouter, HTTPException, Query

                router = APIRouter(tags=["estate-kit"])

                def _fixtures() -> Dict[str, Any]:
                    path = Path(__file__).resolve().parents[2] / "data" / "demo" / "estate_fixtures.json"
                    if not path.is_file():
                        raise HTTPException(status_code=404, detail="demo fixtures missing")
                    return json.loads(path.read_text(encoding="utf-8"))

                def _dual_rag_meta() -> Dict[str, Any]:
                    path = Path(__file__).resolve().parents[2] / "docs" / "rag" / "dual_rag.json"
                    if path.is_file():
                        return json.loads(path.read_text(encoding="utf-8"))
                    return {}

                @router.get("/v1/estate/demo")
                def estate_demo() -> Dict[str, Any]:
                    data = _fixtures()
                    return {
                        "ok": True,
                        "fixture_id": data.get("fixture_id"),
                        "properties": data.get("properties") or [],
                        "vendors": data.get("vendors") or [],
                        "staff": data.get("staff") or [],
                        "maintenance_calendar": data.get("maintenance_calendar") or [],
                    }

                @router.get("/v1/estate/properties")
                def list_properties() -> Dict[str, Any]:
                    props = _fixtures().get("properties") or []
                    return {"count": len(props), "properties": props}

                @router.get("/v1/estate/vendors")
                def list_vendors() -> Dict[str, Any]:
                    vendors = _fixtures().get("vendors") or []
                    return {"count": len(vendors), "vendors": vendors}

                @router.get("/v1/estate/staff")
                def list_staff() -> Dict[str, Any]:
                    staff = _fixtures().get("staff") or []
                    return {"count": len(staff), "staff": staff}

                @router.get("/v1/estate/maintenance")
                def maintenance_calendar() -> Dict[str, Any]:
                    cal = _fixtures().get("maintenance_calendar") or []
                    return {"count": len(cal), "work_orders": cal}

                @router.get("/v1/rag/dual")
                def dual_rag_status() -> Dict[str, Any]:
                    return {"ok": True, "config": _dual_rag_meta()}

                @router.get("/v1/rag/query")
                def dual_rag_query(
                    q: str = Query(..., min_length=1),
                    layer: Optional[int] = Query(None, ge=1, le=2),
                ) -> Dict[str, Any]:
                    """Fixture-backed dual RAG with cited sources (certification demo)."""
                    data = _fixtures()
                    needle = q.lower()
                    layers = []
                    if layer in (None, 1):
                        layers.append(1)
                    if layer in (None, 2):
                        layers.append(2)
                    hits: List[Dict[str, Any]] = []
                    for lyr in layers:
                        docs = data.get("sop_corpus" if lyr == 1 else "estate_documents") or []
                        for doc in docs:
                            text = str(doc.get("text") or "")
                            title = str(doc.get("title") or "")
                            if needle in text.lower() or needle in title.lower() or any(
                                tok in text.lower() for tok in needle.split() if len(tok) > 3
                            ):
                                hits.append(
                                    {
                                        "layer": lyr,
                                        "doc_id": doc.get("doc_id"),
                                        "title": title,
                                        "excerpt": text[:240],
                                        "citation": {
                                            "source_id": doc.get("doc_id"),
                                            "layer": lyr,
                                            "property_id": doc.get("property_id"),
                                        },
                                    }
                                )
                    return {
                        "ok": True,
                        "query": q,
                        "layers_searched": layers,
                        "hit_count": len(hits),
                        "hits": hits,
                        "config": _dual_rag_meta(),
                    }
                '''
            ),
            encoding="utf-8",
        )

        # SPA deep-link stubs for estate modules (cold-start friendly)
        spa = out / "frontend" / "src" / "routes"
        spa.mkdir(parents=True, exist_ok=True)
        (spa / "deepLinks.ts").write_text(
            "// Factory-generated deep links for Steward SPA\n"
            "export const DEEP_LINKS = {\n"
            "  home: '/',\n"
            "  registry: '/registry',\n"
            "  houseManual: '/house-manual',\n"
            "  maintenance: '/maintenance',\n"
            "  vendors: '/vendors',\n"
            "  staff: '/staff',\n"
            "  principal: '/principal',\n"
            "  onboarding: '/onboarding',\n"
            "  rag: '/rag',\n"
            "  resident: '/resident',\n"
            "} as const;\n"
            "\n"
            "/** Cold-start retry hint for Render free-tier spin-up. */\n"
            "export const COLD_START = {\n"
            "  retries: 3,\n"
            "  backoffMs: [1000, 3000, 8000],\n"
            "  message: 'Service waking up — retrying…',\n"
            "};\n",
            encoding="utf-8",
        )

    def _write_runtime_packaging(self, out: Path) -> None:
        """Emit Dockerfile + Procfile so generated products are Render-deployable."""
        (out / "Dockerfile").write_text(
            "FROM python:3.12-slim\n"
            "WORKDIR /app\n"
            "ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1\n"
            "COPY requirements.txt .\n"
            "RUN pip install --no-cache-dir -r requirements.txt\n"
            "COPY . .\n"
            "ENV PYTHONPATH=/app\n"
            "EXPOSE 8000\n"
            'CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]\n',
            encoding="utf-8",
        )
        (out / "Procfile").write_text(
            "web: uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8000}\n",
            encoding="utf-8",
        )
        (out / "render.yaml").write_text(
            f"""services:
  - type: web
    name: {self.blueprint.product_id}
    runtime: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: RESIDENT_ENGINEER_ENABLED
        value: "true"
      - key: PYTHONPATH
        value: /app
""",
            encoding="utf-8",
        )

    def _write_actions(self, out: Path) -> list:
        actions_dir = out / "app" / "actions"
        actions_dir.mkdir(parents=True, exist_ok=True)
        specs = []
        for cap in self.plan.capabilities:
            action_name = cap.capability_id.replace("-", "_")
            domain = self.blueprint.vertical.replace("-", "_")
            # action_id must be domain.action
            action_id = f"{domain}.{action_name}"
            specs.append(
                {
                    "action_id": action_id,
                    "capability_id": cap.capability_id,
                    "strategy": cap.strategy,
                    "block_ids": cap.block_ids,
                    "notes": cap.notes,
                }
            )
            mod = actions_dir / f"{action_name}.py"
            blocks_list = ", ".join(cap.block_ids) or "(none — kernel/GENERATE)"
            mod.write_text(
                f'''"""Generated action module for {action_id} (strategy={cap.strategy}).

Uses cerebrum_product_kernel ActionOutcome patterns. Durable logic belongs in
Factory templates / dual-registered blocks — regenerate rather than hand-edit.
"""

from __future__ import annotations

from typing import Any, Dict, List

from app.cerebrum_product_kernel.contract.models import (
    ActionEvidence,
    ActionOutcome,
    ActionStatus,
)

ACTION_ID = "{action_id}"
CAPABILITY_ID = "{cap.capability_id}"
STRATEGY = "{cap.strategy}"
BLOCK_IDS: List[str] = {cap.block_ids!r}


async def handle(context: Dict[str, Any], arguments: Dict[str, Any]) -> Dict[str, Any]:
    """Execute capability with kernel-shaped outcome (not a freehand echo)."""
    tenant_id = context.get("tenant_id")
    if not tenant_id:
        outcome = ActionOutcome(
            status=ActionStatus.PERMISSION_DENIED,
            error_code="missing_tenant",
            error_message="tenant_id is required in trusted context",
        )
        return outcome.to_dict()

    if STRATEGY == "UNSUPPORTED":
        outcome = ActionOutcome(
            status=ActionStatus.UNSUPPORTED,
            error_code="unsupported_capability",
            error_message=f"capability {{CAPABILITY_ID}} is UNSUPPORTED",
        )
        return outcome.to_dict()

    evidence = [
        ActionEvidence(
            source_id=bid,
            filename=f"block:{{bid}}",
            excerpt=f"Resolved via dual-registered block {{bid}}",
            metadata={{"strategy": STRATEGY}},
        )
        for bid in BLOCK_IDS
    ]
    output = {{
        "action_id": ACTION_ID,
        "capability_id": CAPABILITY_ID,
        "strategy": STRATEGY,
        "block_ids": BLOCK_IDS,
        "arguments": arguments or {{}},
        "tenant_id": tenant_id,
        "result": {{
            "ok": True,
            "summary": f"{{CAPABILITY_ID}} executed via Factory template ({{STRATEGY}})",
            "blocks_used": BLOCK_IDS,
        }},
    }}
    outcome = ActionOutcome.success(output, evidence=evidence)
    return outcome.to_dict()
''',
                encoding="utf-8",
            )
        (actions_dir / "__init__.py").write_text(
            "ACTION_CATALOG = " + json.dumps(specs, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        return specs

    def _write_hats(self, out: Path) -> list:
        manifests = build_hat_manifests(self.blueprint, self.plan)
        hats_dir = out / "app" / "agents" / "manifests"
        hats_dir.mkdir(parents=True, exist_ok=True)
        index = []
        for m in manifests:
            fname = m["agent_id"].replace(".", "_") + ".json"
            (hats_dir / fname).write_text(
                json.dumps(m, indent=2, sort_keys=True) + "\n", encoding="utf-8"
            )
            index.append({"agent_id": m["agent_id"], "kind": m["kind"], "file": fname})
        (out / "app" / "agents" / "__init__.py").write_text(
            "HAT_INDEX = " + json.dumps(index, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        return manifests

    def _write_workflows(self, out: Path) -> list:
        workflows = build_workflows(self.blueprint, self.plan)
        wf_dir = out / "app" / "workflows"
        wf_dir.mkdir(parents=True, exist_ok=True)
        (wf_dir / "workflows.json").write_text(
            json.dumps(workflows, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
        (wf_dir / "__init__.py").write_text(
            "WORKFLOWS = " + json.dumps(workflows, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        return workflows

    def _write_ui_stub(self, out: Path) -> None:
        ui = out / "frontend" / "src"
        modules_dir = ui / "modules"
        modules_dir.mkdir(parents=True, exist_ok=True)
        modules = self.blueprint.ui_modules or ["command_center"]
        cap_ids = [c.capability_id for c in self.plan.capabilities]
        for mod in modules:
            safe = re.sub(r"[^a-zA-Z0-9_]", "_", mod)
            component = safe.title().replace("_", "") + "Module"
            (modules_dir / f"{safe}.tsx").write_text(
                f"""/* Generated UI module: {mod} — Factory template, regenerate-only. */
import {{ useEffect, useState }} from "react";

const MODULE_ID = "{mod}";
const PRODUCT_ID = "{self.blueprint.product_id}";
const CAPABILITIES = {json.dumps(cap_ids)};

export default function {component}() {{
  const [health, setHealth] = useState<string>("pending");
  useEffect(() => {{
    fetch("/health")
      .then((r) => (r.ok ? "ok" : "degraded"))
      .catch(() => "unreachable")
      .then(setHealth);
  }}, []);
  return (
    <section data-module={{MODULE_ID}} data-product={{PRODUCT_ID}}>
      <header>
        <h2>{{MODULE_ID}}</h2>
        <p>Runtime health: {{health}}</p>
      </header>
      <ul>
        {{CAPABILITIES.map((id) => (
          <li key={{id}} data-capability={{id}}>
            {{id}}
          </li>
        ))}}
      </ul>
    </section>
  );
}}
""",
                encoding="utf-8",
            )
        imports = "\n".join(
            f"import {re.sub(r'[^a-zA-Z0-9_]', '_', m).title().replace('_', '')}Module "
            f"from './modules/{re.sub(r'[^a-zA-Z0-9_]', '_', m)}';"
            for m in modules
        )
        renders = "\n".join(
            f"      <{re.sub(r'[^a-zA-Z0-9_]', '_', m).title().replace('_', '')}Module />"
            for m in modules
        )
        (ui / "App.tsx").write_text(
            f"/* Generated UI shell for {self.blueprint.product_name} */\n"
            f"{imports}\n"
            f"export default function App(){{\n"
            f"  return (\n"
            f"    <main data-product=\"{self.blueprint.product_id}\">\n"
            f"      <h1>{self.blueprint.product_name}</h1>\n"
            f"      <p>{self.blueprint.summary}</p>\n"
            f"{renders}\n"
            f"    </main>\n"
            f"  )\n"
            f"}}\n",
            encoding="utf-8",
        )
        (out / "frontend" / "package.json").write_text(
            json.dumps(
                {"name": self.blueprint.product_id, "private": True, "version": "1.0.0"},
                indent=2,
            )
            + "\n",
            encoding="utf-8",
        )

    def _write_connectors(self, out: Path) -> None:
        conn = out / "app" / "connectors"
        conn.mkdir(parents=True, exist_ok=True)
        items = []
        for c in self.blueprint.connectors:
            items.append({"id": c, "status": "not_implemented", "honest": True})
            (conn / f"{c}.py").write_text(
                f'"""Honest stub connector: {c}."""\n\nSTATUS = "not_implemented"\n',
                encoding="utf-8",
            )
        (conn / "__init__.py").write_text(
            "CONNECTORS = " + json.dumps(items, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )

    def _copy_referenced_blocks(self, out: Path) -> None:
        dest = out / "vendor" / "blocks"
        dest.mkdir(parents=True, exist_ok=True)
        mirror = Path(__file__).resolve().parent / "vendor_blocks_mirror"
        registry = Path(self.blocks_root) / "block_registry" if self.blocks_root else None
        for bid in self.plan.dual_registered_blocks:
            src = registry / bid if registry else None
            if src and src.exists():
                shutil.copytree(src, dest / bid, dirs_exist_ok=True)
                continue
            # Fall back to the vendor mirror when the external registry is unavailable
            mirror_src = mirror / bid
            if mirror_src.exists():
                shutil.copytree(mirror_src, dest / bid, dirs_exist_ok=True)

    def _write_blueprint_copy(self, out: Path) -> None:
        docs = out / "docs" / "blueprint"
        docs.mkdir(parents=True, exist_ok=True)
        (docs / "product_blueprint.json").write_text(
            json.dumps(blueprint_to_dict(self.blueprint), indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )

    def _write_edge_profile(self, out: Path) -> None:
        profile = {
            "edge_profile": self.blueprint.edge_profile,
            "human_authority": self.blueprint.human_authority,
            "isolation": "property",
            "pii_in_learning": False,
        }
        (out / "docs" / "edge_profile.json").write_text(
            json.dumps(profile, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )

    def _write_certification_scaffold(self, out: Path) -> None:
        cert = out / "docs" / "certification"
        cert.mkdir(parents=True, exist_ok=True)
        report = {
            "PRODUCT_CERTIFIED": "pending",
            "RESIDENT_AGENT_CERTIFIED": "pending",
            "incomplete_until_both": True,
            "factory_scenario": self.blueprint.factory_scenario.value,
        }
        (cert / "dual_certification.json").write_text(
            json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )


def git_head(repo: Path) -> str:
    try:
        r = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=repo,
            capture_output=True,
            text=True,
            check=False,
        )
        if r.returncode == 0:
            return r.stdout.strip()
    except OSError:
        pass
    return "unknown"
