"""Domain Intelligence Compiler — turn a scout report into a candidate pack.

The compiler NEVER certifies. Every artifact it generates carries
``certification: candidate`` and full donor provenance; promotion to
technically_verified / domain_approved happens only through the Store's
gate process (mission Phase 4 rule: "The compiler must not silently
certify extracted content").
"""

from __future__ import annotations

import hashlib
import json
import re
from typing import Any, Dict, List

from .scout import ScoutReport


def _slug(symbol: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_]+", "_", symbol).strip("_").lower() or "artifact"


def _provenance(
    donor_repo: str,
    donor_commit: str,
    d: Any,
    extra: Dict[str, str] | None = None,
) -> Dict[str, str]:
    prov: Dict[str, str] = {
        "donor_repo": donor_repo,
        "donor_commit": donor_commit,
        "donor_path": d.path,
        "donor_symbol": d.symbol,
        "donor_line": str(d.line),
        "test_evidence": "|".join(d.test_evidence) if d.test_evidence else "none",
        "classification": "VERIFIED" if d.test_evidence else "EXECUTABLE_UNVERIFIED",
        "extraction": "domain-intelligence-compiler (scout)",
    }
    if extra:
        prov.update(extra)
    return prov


class CandidatePackGenerator:
    """Compile a ScoutReport into a schema-valid candidate Domain Pack dict."""

    def __init__(
        self,
        domain_id: str,
        name: str,
        donor_repo: str,
        donor_commit: str,
        description: str = "",
        version: str = "0.1.0",
    ) -> None:
        self.domain_id = domain_id
        self.name = name
        self.donor_repo = donor_repo
        self.donor_commit = donor_commit
        self.description = description or (
            f"Candidate pack generated by the domain-intelligence-compiler "
            f"from {donor_repo}@{donor_commit}. Every artifact is UNVERIFIED "
            f"until the store gate promotes it."
        )
        self.version = version

    def detect_duplicates(self, report: ScoutReport) -> List[Dict[str, Any]]:
        seen: Dict[tuple, List[str]] = {}
        for d in report.discoveries:
            seen.setdefault((d.kind, d.symbol), []).append(f"{d.path}:{d.line}")
        return [
            {"kind": k, "symbol": s, "locations": locs}
            for (k, s), locs in seen.items()
            if len(locs) > 1
        ]

    def detect_contradictions(self, report: ScoutReport) -> List[Dict[str, Any]]:
        # A contradiction candidate: the same symbol implemented in more than
        # one file (two authorities for one name). The compiler flags, never
        # resolves silently.
        return [
            {"kind": k, "symbol": s, "locations": locs, "resolution": "domain_review_required"}
            for (k, s), locs in [
                ((k, s), [f"{d.path}:{d.line}" for d in ds])
                for (k, s), ds in _group_by_symbol(report).items()
            ]
            if len(locs) > 1
        ]

    def missing_test_templates(self, report: ScoutReport) -> Dict[str, str]:
        templates: Dict[str, str] = {}
        for d in report.discoveries:
            if d.test_evidence:
                continue
            symbol = _slug(d.symbol)
            templates[f"test_candidate_{d.kind}_{symbol}.py"] = (
                f"# Generated missing-test template for {d.kind} '{d.symbol}'\n"
                f"# Donor: {self.donor_repo}@{self.donor_commit} "
                f"{d.path}:{d.line}\n"
                f"# TODO(domain_review): bind the donor implementation and add a\n"
                f"# known-answer case. Until this passes, the artifact stays\n"
                f"# EXECUTABLE_UNVERIFIED and can never be promoted.\n\n"
                f"def test_{d.kind}_{symbol}_known_answer():\n"
                f'    raise NotImplementedError("no oracle yet — see provenance")\n'
            )
        return templates

    def role_matrix_draft(self, report: ScoutReport) -> List[Dict[str, Any]]:
        drafts = []
        for d in report.discoveries:
            if d.kind != "approval":
                continue
            drafts.append(
                {
                    "action": d.symbol,
                    "risk_tier": "domain_review_required",
                    "requester_roles": [],
                    "approver_roles": [],
                    "note": (
                        "Compiler draft — roles unknown. A domain expert must "
                        f"fill this in. Evidence: {d.path}:{d.line}"
                    ),
                }
            )
        return drafts

    def workflow_diagram(self, report: ScoutReport) -> Dict[str, str]:
        diagrams: Dict[str, str] = {}
        for d in report.discoveries:
            if d.kind != "workflow":
                continue
            diagrams[d.symbol] = (
                "stateDiagram-v2\n"
                "    [*] --> UNKNOWN_STATES\n"
                f"    note right of UNKNOWN_STATES\n"
                f"        candidate workflow '{d.symbol}'\\n"
                f"        {d.path}:{d.line}\\n"
                f"        transitions not yet extracted\\n"
                f"        — domain review required\n"
                "    end note\n"
            )
        return diagrams

    def oracle_templates(self, report: ScoutReport) -> Dict[str, str]:
        oracles: Dict[str, str] = {}
        for d in report.discoveries:
            if d.kind != "formula":
                continue
            oracles[d.symbol] = (
                f"# Oracle template for formula '{d.symbol}' "
                f"({d.path}:{d.line})\n"
                f"# Bind the donor implementation, then assert a known answer.\n"
                f"def oracle_{_slug(d.symbol)}(*args, **kwargs):\n"
                f'    raise NotImplementedError("bind donor symbol first")\n'
            )
        return oracles

    def compile(self, report: ScoutReport) -> Dict[str, Any]:
        formulas: List[Dict[str, Any]] = []
        rules: List[Dict[str, Any]] = []
        workflows: List[Dict[str, Any]] = []
        approvals: List[Dict[str, Any]] = []
        for d in report.discoveries:
            prov = _provenance(self.donor_repo, self.donor_commit, d)
            if d.kind == "formula":
                formulas.append(
                    {
                        "formula_id": f"{self.domain_id}.{_slug(d.symbol)}",
                        "name": d.symbol,
                        "domain": self.domain_id,
                        "version": self.version,
                        "description": (
                            f"Candidate extracted from {d.path}:{d.line} — "
                            "expression/inputs/output not yet extracted; "
                            "review before use."
                        ),
                        "certification": "candidate",
                        "provenance": prov,
                    }
                )
            elif d.kind == "rule":
                rules.append(
                    {
                        "rule_id": f"{self.domain_id}.rule.{_slug(d.symbol)}",
                        "version": self.version,
                        "decision": {
                            "action": "candidate — conditions not yet extracted",
                        },
                        "refusal_behavior": "refuse",
                        "certification": "candidate",
                        "provenance": prov,
                    }
                )
            elif d.kind == "workflow":
                workflows.append(
                    {
                        "workflow_id": f"{self.domain_id}.workflow.{_slug(d.symbol)}",
                        "version": self.version,
                        "certification": "candidate",
                        "provenance": prov,
                    }
                )
            elif d.kind == "approval":
                approvals.append(
                    {
                        "action": d.symbol,
                        "version": self.version,
                        "self_approval": "prohibited",
                        "payload_binding": "required",
                        "replay_prevention": "required",
                        "audit_required": True,
                        "certification": "candidate",
                        "provenance": prov,
                    }
                )
        duplicates = self.detect_duplicates(report)
        contradictions = self.detect_contradictions(report)
        return {
            "manifest": {
                "domain_id": self.domain_id,
                "version": self.version,
                "name": self.name,
                "description": self.description,
                "certification": "candidate",
                "donor_repo": self.donor_repo,
                "donor_commit": self.donor_commit,
            },
            "ontology": {
                "compiler_note": "not yet extracted — domain review required"
            },
            "entities": {
                "compiler_note": "not yet extracted — domain review required"
            },
            "permissions": {
                "compiler_note": "not yet extracted — domain review required"
            },
            "evidence_policy": {
                "compiler_note": "not yet extracted — domain review required"
            },
            "authority_sources": {
                "compiler_note": "not yet extracted — domain review required"
            },
            "refusal_policy": {
                "compiler_note": "not yet extracted — domain review required"
            },
            "formulas": formulas,
            "rules": rules,
            "decision_tables": [],
            "workflows": workflows,
            "approvals": approvals,
            "actions": {},
            "verification_oracles": self.oracle_templates(report),
            "fixtures": {},
            "tests": {
                "missing_test_templates": self.missing_test_templates(report),
                "workflow_diagrams": self.workflow_diagram(report),
                "role_matrix_drafts": self.role_matrix_draft(report),
            },
        }

    def compiler_report(self, report: ScoutReport) -> Dict[str, Any]:
        return {
            "duplicates": self.detect_duplicates(report),
            "contradictions": self.detect_contradictions(report),
            "certification_policy": (
                "all artifacts generated as 'candidate' — the compiler "
                "never certifies; promotion requires the store gate"
            ),
        }

    def digest(self, pack: Dict[str, Any]) -> str:
        canonical = json.dumps(pack, sort_keys=True, default=str)
        return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def _group_by_symbol(report: ScoutReport) -> Dict[tuple, List[Any]]:
    grouped: Dict[tuple, List[Any]] = {}
    for d in report.discoveries:
        grouped.setdefault((d.kind, d.symbol), []).append(d)
    return grouped
